### ISSUE TITLE
Error when running first example

### ISSUE THREAD

**Issue by lpassarella** [fdac18/Practice0#4]
Hi everyone,

I'm not sure if anyone else is having this issue, but every time I try to the first example in the jupyter notebook I get this error:

> ERROR:root:Internal Python error in the inspect module.
> Below is the traceback from this internal error.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2961, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-64-c92c3de78c65>", line 8, in <module>
>     import pandas as pd
>   File "/usr/local/lib/python3.5/dist-packages/pandas/__init__.py", line 42, in <module>
>     from pandas.core.api import *
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/api.py", line 10, in <module>
>     from pandas.core.groupby.groupby import Grouper
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/groupby/__init__.py", line 2, in <module>
>     from pandas.core.groupby.groupby import (
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/groupby/groupby.py", line 49, in <module>
>     from pandas.core.frame import DataFrame
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 74, in <module>
>     from pandas.core.series import Series
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/series.py", line 67, in <module>
>     import pandas.core.ops as ops
> AttributeError: module 'pandas' has no attribute 'core'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 1863, in showtraceback
>     stb = value._render_traceback_()
> AttributeError: 'AttributeError' object has no attribute '_render_traceback_'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py", line 1095, in get_records
>     return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
>   File "/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py", line 311, in wrapped
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py", line 345, in _fixed_getinnerframes
>     records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
>   File "/usr/lib/python3.5/inspect.py", line 1453, in getinnerframes
>     frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
>   File "/usr/lib/python3.5/inspect.py", line 1410, in getframeinfo
>     filename = getsourcefile(frame) or getfile(frame)
>   File "/usr/lib/python3.5/inspect.py", line 672, in getsourcefile
>     if getattr(getmodule(object, filename), '__loader__', None) is not None:
>   File "/usr/lib/python3.5/inspect.py", line 701, in getmodule
>     file = getabsfile(object, _filename)
>   File "/usr/lib/python3.5/inspect.py", line 685, in getabsfile
>     return os.path.normcase(os.path.abspath(_filename))
>   File "/usr/lib/python3.5/posixpath.py", line 361, in abspath
>     cwd = os.getcwd()
> FileNotFoundError: [Errno 2] No such file or directory

I thought it might be the version of python I am using, and when I checked in my terminal it said I am running Python 2.7.12, however my notebook says I'm using Python 3.5 and I have no option to change it.

It similarly breaks with matplotlib when I try to run the histogram file. I was wondering if anyone had any ideas on how to fix this because I am unable to plot the gaussian problem.

**Comment by audrism** [comment]
I just logged in to your docker container and the Jupyter notebook seems to work fine. 

do you use port 9237? 

```
host da2
  hostname da2.eecs.utk.edu
  user lpassare
  port 9237
  IdentityFile ~/.ssh/id_rsa
  LocalForward 8888 127.0.0.1:8888
```

http://127.0.0.1:8888/notebooks/Practice0/lpassare.ipynb

**Comment by audrism** [comment]
Perhaps you already have Jupyter on your own laptop running?
If so you need to change the port, e.g., 
http://127.0.0.1:8889/notebooks/Practice0/lpassare.ipynb

and also in .ssh/config
LocalForward 8889 127.0.0.1:8888

**Comment by lpassarella** [comment]
I did have Jupyter on my computer running.

It works fine now, thank you!
